name: Update Website Data

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Setup R environment
        run: |
          install.packages("renv")
          install.packages("tidyverse")
          install.packages("httr")
          install.packages("rlang")
          install.packages("jsonlite")
        shell: Rscript {0}

      - name: Cache R environment
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore R environment
        run: renv::restore()
        shell: Rscript {0}

      - name: Update data
        run: source("github-action-update-website-data.R")
        shell: Rscript {0}

      - name: Commit data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Automatic update" && git push)
